// components/login/Footer.vue
<template>
  <div class="footer">
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          <ul class="footer-links">
            <li>
              <a href="mailto:vragen@uitdatabank.be" class="footer-link"
                >Contacteer ons</a
              >
            </li>
            <li>
              <a
                href="http://www.publiq.be/nl/project/uitdatabank"
                class="footer-link"
                >Over UiTdatabank</a
              >
            </li>
            <li>
              <a href="http://documentatie.uitdatabank.be" class="footer-link"
                >Voor ontwikkelaars</a
              >
            </li>
            <li>
              <!-- TODO link to conditions in correct language -->
              <a href="http://www.publiq.be/nl" class="footer-link"
                >Gebruiksvoorwaarden</a
              >
              |
              <a href="http://www.publiq.be/nl/" class="footer-link">Privacy</a>
            </li>
          </ul>
        </div>

        <div class="col-sm-6">
          <p class="footer-by">
            <span>Een product van</span>
            <a href="http://www.publiq.be" class="footer-link">publiq vzw</a>
          </p>

          <img
            v-show="$i18n.locale === 'nl'"
            src="~/assets/vlaanderen-logo.png"
            class="logo-flanders-full"
          />
          <img
            v-show="$i18n.locale === 'fr'"
            src="~/assets/flanders-logo.png"
            class="logo-flanders-full"
          />
          <p class="language-switcher">
            <!-- TODO language switcher -->
            <a @click="setLocale('nl')">Nederlands</a>
            <a @click="setLocale('fr')">Français</a>
          </p>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
  export default {
    methods: {
      setLocale(locale) {
        this.$i18n.locale = locale;
      },
    },
  };
</script>

<style lang="scss" scoped>
  .footer {
    padding: 30px 0;
    background-color: #ccc;
  }
  .footer-links {
    padding-left: 0;
    list-style: none;
    margin: 0;
  }

  .footer-link {
    color: #555;
    text-decoration: underline;
  }

  .footer-by {
    text-align: right;
  }

  .logo-flanders-full {
    float: right;
    width: 150px;
    margin-bottom: 15px;
  }

  .logo-flanders {
    display: inline-block;
    float: right;

    &::after {
      background-size: 15px 15px;
      background: transparent url('/images/footer/vlaamse_overheid.png')
        no-repeat;
      content: '';
      display: inline-block;
      height: 20px;
      margin-left: 6px;
      margin-top: -10px;
      width: 13px;
      white-space: nowrap;
      vertical-align: bottom;
    }
  }

  .language-switcher {
    text-align: right;
    clear: both;
    margin-top: 12px;

    a {
      color: #004f94;
      cursor: pointer;
      text-decoration: none;
    }
  }
</style>

// src/components/pages/login/Footer.tsx
import type { ElementType } from 'react';
import { useTranslation } from 'react-i18next';

import { Box } from '@/ui/Box';
import { Button, ButtonVariants } from '@/ui/Button';
import { Image } from '@/ui/Image';
import { Inline } from '@/ui/Inline';
import { Link } from '@/ui/Link';
import { List } from '@/ui/List';
import { Stack } from '@/ui/Stack';

const LanguageSwitcherButton = (props) => (
  <Button
    {...props}
    variant={ButtonVariants.UNSTYLED}
    css={`
      text-decoration: underline;
      color: #004f94;
      &:hover {
        color: #222;
      }
    `}
  />
);

const FooterLink = (props) => (
  <Link
    {...props}
    css={`
      text-decoration: underline;
      color: #555;
      &:hover {
        color: #222;
      }
    `}
  />
);

type Props = {
  wrapper?: ElementType;
  onChangeLanguage?: (language: string) => () => Promise<boolean>;
  isLogoVisible?: boolean;
  isLanguageSwitcherVisible?: boolean;
};

const Footer = ({
  wrapper: Wrapper,
  onChangeLanguage,
  isLogoVisible,
  isLanguageSwitcherVisible,
}: Props) => {
  const { t, i18n } = useTranslation();

  return (
    <Wrapper>
      <Stack alignItems="flex-start">
        <List alignItems={{ xs: 'center' }}>
          <List.Item>
            <FooterLink href="mailto:vragen@uitdatabank.be">
              {t('footer.contact')}
            </FooterLink>
          </List.Item>
          <List.Item>
            <FooterLink href="http://www.publiq.be/nl/project/uitdatabank">
              {t('footer.about')}
            </FooterLink>
          </List.Item>
          <List.Item>
            <FooterLink href="http://documentatie.uitdatabank.be">
              {t('footer.dev')}
            </FooterLink>
          </List.Item>
          <List.Item>
            <Inline spacing={3}>
              <FooterLink
                href={`http://www.publiq.be/${i18n.language}/${t(
                  'footer.legal_path',
                )}`}
              >
                {t('footer.legal')}
              </FooterLink>
              <FooterLink href="http://www.publiq.be/nl/privacy-uitdatabank">
                {t('footer.privacy')}
              </FooterLink>
            </Inline>
          </List.Item>
        </List>
      </Stack>

      <Stack
        spacing={3}
        alignItems={{ default: 'flex-end', xs: 'center' }}
        justifyContent="flex-start"
      >
        <Inline as="p" spacing={2} className="footer-by">
          <Box as="span">{t('footer.by')}</Box>
          <FooterLink href="http://www.publiq.be">publiq vzw</FooterLink>
        </Inline>
        {isLogoVisible && (
          <Image
            alt="logo vlaanderen"
            src={`/assets/${t('main.flanders_image')}`}
            width={150}
          />
        )}
        {isLanguageSwitcherVisible && (
          <Inline>
            <LanguageSwitcherButton onClick={onChangeLanguage('nl')}>
              Nederlands
            </LanguageSwitcherButton>
            <LanguageSwitcherButton
              variant={ButtonVariants.UNSTYLED}
              onClick={onChangeLanguage('fr')}
            >
              Français
            </LanguageSwitcherButton>
          </Inline>
        )}
      </Stack>
    </Wrapper>
  );
};

Footer.defaultProps = {
  isLogoVisible: true,
  isLanguageSwitcherVisible: true,
  wrapper: (props) => (
    <Inline width="100%" justifyContent="space-between" {...props} />
  ),
};

export { Footer };
