// src/layouts/Sidebar.tsx
import getConfig from 'next/config';
import { useRouter } from 'next/router';
import type { ReactNode } from 'react';
import { memo, useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { useTranslation } from 'react-i18next';
import { useQueryClient } from 'react-query';

import { useGetAnnouncementsQuery } from '@/hooks/api/announcements';
import { useGetEventsToModerateQuery } from '@/hooks/api/events';
import { useGetPermissionsQuery, useGetRolesQuery } from '@/hooks/api/user';
import { useCookiesWithOptions } from '@/hooks/useCookiesWithOptions';
import { FeatureFlags, useFeatureFlag } from '@/hooks/useFeatureFlag';
import { useLocalStorage } from '@/hooks/useLocalStorage';
import { useMatchBreakpoint } from '@/hooks/useMatchBreakpoint';
import type { Values } from '@/types/Values';
import { Badge } from '@/ui/Badge';
import { Button } from '@/ui/Button';
import { Icons } from '@/ui/Icon';
import { Image } from '@/ui/Image';
import { Inline } from '@/ui/Inline';
import { Link } from '@/ui/Link';
import type { ListProps } from '@/ui/List';
import { List } from '@/ui/List';
import { Logo, LogoVariants } from '@/ui/Logo';
import { Stack } from '@/ui/Stack';
import { Text } from '@/ui/Text';
import { Breakpoints, getValueFromTheme } from '@/ui/theme';
import { Title } from '@/ui/Title';

import { Announcements, AnnouncementStatus } from './Announcements';
import { JobLogger, JobLoggerStates } from './joblogger/JobLogger';
import { JobLoggerStateIndicator } from './joblogger/JobLoggerStateIndicator';

const getValueForMenuItem = getValueFromTheme('menuItem');
const getValueForSidebar = getValueFromTheme('sidebar');
const getValueForMenu = getValueFromTheme('menu');

const PermissionTypes = {
  AANBOD_BEWERKEN: 'AANBOD_BEWERKEN',
  AANBOD_MODEREREN: 'AANBOD_MODEREREN',
  AANBOD_VERWIJDEREN: 'AANBOD_VERWIJDEREN',
  ORGANISATIES_BEWERKEN: 'ORGANISATIES_BEWERKEN',
  ORGANISATIES_BEHEREN: 'ORGANISATIES_BEHEREN',
  GEBRUIKERS_BEHEREN: 'GEBRUIKERS_BEHEREN',
  LABELS_BEHEREN: 'LABELS_BEHEREN',
  VOORZIENINGEN_BEWERKEN: 'VOORZIENINGEN_BEWERKEN',
  PRODUCTIES_AANMAKEN: 'PRODUCTIES_AANMAKEN',
  FILMS_AANMAKEN: 'FILMS_AANMAKEN',
} as const;

type MenuItemType = {
  href?: string;
  iconName: Values<typeof Icons>;
  suffix?: ReactNode;
  children: string;
  onClick?: () => void;
  visible?: boolean;
  permission?: Values<typeof PermissionTypes>;
};

type MenuItemProps = Omit<MenuItemType, 'permission'>;

const MenuItem = memo(
  ({
    href,
    iconName,
    suffix,
    children: label,
    onClick,
    visible = true,
  }: MenuItemProps) => {
    if (!visible) {
      return null;
    }

    const Component = href ? Link : Button;

    return (
      <List.Item>
        <Component
          width="100%"
          variant="unstyled"
          padding={2}
          href={href}
          iconName={iconName}
          suffix={suffix}
          onClick={onClick}
          backgroundColor={{
            default: 'none',
            hover: getValueForMenuItem('hover.backgroundColor'),
          }}
          spacing={{ default: 3, s: 0 }}
          stackOn={Breakpoints.S}
          customChildren
          title={label}
        >
          <Text
            flex={1}
            css={`
              white-space: nowrap;
              overflow: hidden;
              text-overflow: ellipsis;
            `}
            fontSize={{ s: '9px' }}
            textAlign={{ default: 'left', s: 'center' }}
          >
            {label}
          </Text>
        </Component>
      </List.Item>
    );
  },
);

MenuItem.displayName = 'MenuItem';

type MenuProps = ListProps & {
  items: MenuItemType[];
  title?: string;
};

const Menu = memo(({ items = [], title, ...props }: MenuProps) => {
  const Content = (contentProps) => (
    <List {...contentProps}>
      {items.map((menuItem, index) => (
        <MenuItem key={index} {...menuItem} />
      ))}
    </List>
  );

  Menu.displayName = 'Menu';

  if (!title) return <Content {...props} />;

  return (
    <Stack spacing={3} {...props}>
      <Title
        opacity={0.5}
        css={`
          font-size: 13px;
          font-weight: 400;
          text-transform: uppercase;
        `}
        textAlign={{ s: 'center' }}
      >
        {title}
      </Title>
      <Content />
    </Stack>
  );
});

type ProfileMenuProps = {
  profileImage?: string;
};

const ProfileMenu = ({ profileImage }: ProfileMenuProps) => {
  const { t } = useTranslation();
  const { cookies, removeAuthenticationCookies } = useCookiesWithOptions([
    'user',
  ]);
  const { publicRuntimeConfig } = getConfig();

  const router = useRouter();
  const queryClient = useQueryClient();

  const loginMenu = [
    {
      iconName: Icons.SIGN_OUT,
      children: t('menu.logout'),
      onClick: async () => {
        removeAuthenticationCookies();
        await queryClient.invalidateQueries('user');

        const getBaseUrl = () =>
          `${window.location.protocol}//${window.location.host}`;

        const queryString = new URLSearchParams({
          destination: getBaseUrl(),
        }).toString();

        router.push(`${publicRuntimeConfig.authUrl}/logout?${queryString}`);
      },
    },
  ];

  return (
    <Inline
      padding={1}
      spacing={2}
      alignItems="center"
      justifyContent="center"
      css={`
        border-top: 1px solid ${getValueForMenu('borderColor')};
      `}
    >
      <Image src={profileImage} width={50} height={50} alt="Profile picture" />
      <Stack as="div" padding={2} spacing={2} flex={1} display={{ s: 'none' }}>
        <Text>{cookies?.user?.username ?? ''}</Text>
        <Menu items={loginMenu} />
      </Stack>
    </Inline>
  );
};

ProfileMenu.defaultProps = {
  profileImage: '/assets/avatar.svg',
};

type NotificationMenuProps = {
  countUnseenAnnouncements: number;
  onClickAnnouncementsButton: () => void;
  onClickJobLoggerButton: () => void;
  jobLoggerState: Values<typeof JobLoggerStates>;
};

const NotificationMenu = memo(
  ({
    countUnseenAnnouncements,
    onClickAnnouncementsButton,
    onClickJobLoggerButton,
    jobLoggerState,
  }: NotificationMenuProps) => {
    const { t, i18n } = useTranslation();

    const notificationMenu = [
      {
        iconName: Icons.GIFT,
        children: t('menu.announcements'),
        suffix: countUnseenAnnouncements > 0 && (
          <Badge>{countUnseenAnnouncements}</Badge>
        ),
        onClick: onClickAnnouncementsButton,
        visible: i18n.language === 'nl',
      },
      {
        iconName: Icons.BELL,
        children: t('menu.notifications'),
        suffix: <JobLoggerStateIndicator state={jobLoggerState} />,
        onClick: onClickJobLoggerButton,
      },
    ];

    return <Menu items={notificationMenu} />;
  },
);

const Sidebar = () => {
  const { t, i18n } = useTranslation();

  const [isReactCreateFeatureFlagEnabled] = useFeatureFlag(
    FeatureFlags.REACT_CREATE,
  );

  const storage = useLocalStorage();

  const [isJobLoggerVisible, setIsJobLoggerVisible] = useState(true);
  const [jobLoggerState, setJobLoggerState] = useState(JobLoggerStates.IDLE);
  const sidebarComponent = useRef();

  const [
    isAnnouncementsModalVisible,
    setIsAnnouncementsModalVisible,
  ] = useState(false);
  const [activeAnnouncementId, setActiveAnnouncementId] = useState();

  const [searchQuery, setSearchQuery] = useState('');

  const getAnnouncementsQuery = useGetAnnouncementsQuery({
    refetchInterval: 60000,
  });

  const rawAnnouncements = getAnnouncementsQuery.data?.data ?? [];
  const getPermissionsQuery = useGetPermissionsQuery();
  const getRolesQuery = useGetRolesQuery();
  const getEventsToModerateQuery = useGetEventsToModerateQuery(searchQuery);
  // @ts-expect-error
  const countEventsToModerate = getEventsToModerateQuery.data?.totalItems || 0;

  const isSmallView = useMatchBreakpoint(Breakpoints.S);

  const handleClickAnnouncement = useCallback(
    (activeAnnouncement) => setActiveAnnouncementId(activeAnnouncement.uid),
    [],
  );

  const toggleIsAnnouncementsModalVisible = useCallback(
    () => setIsAnnouncementsModalVisible((prevValue) => !prevValue),
    [],
  );

  const toggleIsJobLoggerVisible = useCallback(
    () => setIsJobLoggerVisible((prevValue) => !prevValue),
    [],
  );

  useEffect(() => {
    if (isAnnouncementsModalVisible) {
      setActiveAnnouncementId(announcements[0].uid);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isAnnouncementsModalVisible]);

  useEffect(() => {
    if (activeAnnouncementId) {
      const seenAnnouncements = storage.getItem('seenAnnouncements') ?? [];
      if (!seenAnnouncements.includes(activeAnnouncementId)) {
        storage.setItem('seenAnnouncements', [
          ...seenAnnouncements,
          activeAnnouncementId,
        ]);
      }
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [activeAnnouncementId]);

  useEffect(() => {
    if (rawAnnouncements.length === 0) {
      return;
    }

    const seenAnnouncements = storage.getItem('seenAnnouncements') ?? [];
    const cleanedUpSeenAnnouncements = seenAnnouncements.filter(
      (seenAnnouncementId) =>
        rawAnnouncements.find(
          (announcement) => announcement.uid === seenAnnouncementId,
        ),
    );
    storage.setItem('seenAnnouncements', cleanedUpSeenAnnouncements);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [rawAnnouncements]);

  useEffect(() => {
    // @ts-expect-error
    if (!getRolesQuery.data) {
      return;
    }

    // @ts-expect-error
    const validationQuery = getRolesQuery.data
      .map((role) => (role.constraints?.v3 ? role.constraints.v3 : null))
      .filter((constraint) => constraint !== null)
      .join(' OR ');

    setSearchQuery(validationQuery);
    // @ts-expect-error
  }, [getRolesQuery.data]);

  const announcements = useMemo(
    () =>
      rawAnnouncements.map((announcement) => {
        if (activeAnnouncementId === announcement.uid) {
          return { ...announcement, status: AnnouncementStatus.ACTIVE };
        }
        const seenAnnouncements = storage.getItem('seenAnnouncements') ?? [];
        if (seenAnnouncements.includes(announcement.uid)) {
          return { ...announcement, status: AnnouncementStatus.SEEN };
        }
        return { ...announcement, status: AnnouncementStatus.UNSEEN };
      }),
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [rawAnnouncements, activeAnnouncementId],
  );

  const countUnseenAnnouncements = useMemo(
    () =>
      announcements.filter(
        (announcement) => announcement.status === AnnouncementStatus.UNSEEN,
      ).length,
    [announcements],
  );

  const userMenu = [
    {
      href: '/dashboard?tab=events&page=1&sort=created_desc',
      iconName: Icons.HOME,
      children: t('menu.home'),
    },
    {
      href: isReactCreateFeatureFlagEnabled ? '/create' : '/event',
      iconName: Icons.PLUS_CIRCLE,
      children: t('menu.add'),
    },
    {
      href: '/search',
      iconName: Icons.SEARCH,
      children: t('menu.search'),
    },
  ];

  const filteredManageMenu = useMemo(() => {
    // @ts-expect-error
    if (!getPermissionsQuery.data) {
      return [];
    }

    const manageMenu: MenuItemType[] = [
      {
        permission: PermissionTypes.AANBOD_MODEREREN,
        href: '/manage/moderation/overview',
        iconName: Icons.FLAG,
        children: t('menu.validate'),
        suffix: countEventsToModerate > 0 && (
          <Badge>{countEventsToModerate}</Badge>
        ),
      },
      {
        permission: PermissionTypes.GEBRUIKERS_BEHEREN,
        href: '/manage/users/overview',
        iconName: Icons.USER,
        children: t('menu.users'),
      },
      {
        permission: PermissionTypes.GEBRUIKERS_BEHEREN,
        href: '/manage/roles/overview',
        iconName: Icons.USERS,
        children: t('menu.roles'),
      },
      {
        permission: PermissionTypes.LABELS_BEHEREN,
        href: '/manage/labels/overview',
        iconName: Icons.TAG,
        children: t('menu.labels'),
      },
      {
        permission: PermissionTypes.ORGANISATIES_BEHEREN,
        href: '/manage/organizations',
        iconName: Icons.SLIDE_SHARE,
        children: t('menu.organizations'),
      },
      {
        permission: PermissionTypes.PRODUCTIES_AANMAKEN,
        href: '/manage/productions',
        iconName: Icons.LAYER_GROUP,
        children: t('menu.productions'),
      },
      {
        permission: PermissionTypes.FILMS_AANMAKEN,
        href: '/manage/movies/create',
        iconName: Icons.VIDEO,
        children: t('menu.movies'),
        visible: i18n.language === 'nl',
      },
    ];

    return manageMenu.filter((menuItem) => {
      // @ts-expect-error
      return getPermissionsQuery.data.includes(menuItem.permission);
    });
    // @ts-expect-error
  }, [countEventsToModerate, getPermissionsQuery.data, i18n.language, t]);

  return [
    <Stack
      key="sidebar"
      forwardedAs="nav"
      height="100%"
      css={`
        overflow: hidden;
      `}
      width={{ default: '230px', s: '65px' }}
      backgroundColor={getValueForSidebar('backgroundColor')}
      color={getValueForSidebar('color')}
      zIndex={getValueForSidebar('zIndex')}
      padding={{ default: 2, s: 0 }}
      spacing={3}
      ref={sidebarComponent}
      onMouseOver={() => {
        setTimeout(() => {
          if (!sidebarComponent?.current) return;
          if (document.activeElement.tagName !== 'iframe') return;
          // @ts-expect-error
          document.activeElement.blur();
        }, 100);
      }}
    >
      <Link
        justifyContent="center"
        href="/dashboard"
        title={t('menu.home')}
        customChildren
      >
        <Logo
          variant={isSmallView ? LogoVariants.MOBILE : LogoVariants.DEFAULT}
        />
      </Link>
      <Stack
        paddingTop={4}
        spacing={4}
        flex={1}
        css={`
          > :not(:first-child) {
            border-top: 1px solid ${getValueForMenu('borderColor')};
          }
        `}
      >
        <Menu items={userMenu} />
        <Stack
          justifyContent={
            filteredManageMenu.length > 0 ? 'space-between' : 'flex-end'
          }
          flex={1}
        >
          {filteredManageMenu.length > 0 && (
            <Menu items={filteredManageMenu} title={t('menu.management')} />
          )}
          <Stack>
            <NotificationMenu
              countUnseenAnnouncements={countUnseenAnnouncements}
              jobLoggerState={jobLoggerState}
              onClickAnnouncementsButton={toggleIsAnnouncementsModalVisible}
              onClickJobLoggerButton={toggleIsJobLoggerVisible}
            />
            <ProfileMenu />
          </Stack>
        </Stack>
      </Stack>
    </Stack>,
    <JobLogger
      key="joblogger"
      visible={isJobLoggerVisible}
      onClose={() => setIsJobLoggerVisible((oldState) => !oldState)}
      onStatusChange={setJobLoggerState}
    />,
    <Announcements
      key="announcements"
      visible={isAnnouncementsModalVisible}
      announcements={announcements || []}
      onClickAnnouncement={handleClickAnnouncement}
      onClose={toggleIsAnnouncementsModalVisible}
    />,
  ];
};

export { Sidebar };

// components/sidebar.vue
<template>
  <div>
    <div class="sidebar">
      <nuxt-link class="udb-logo-link" to="/dashboard">
        <img src="../assets/udb-logo.svg" alt="Uitdatabank" class="udb-logo" />
        <img
          src="../assets/udb-logo-mobile.svg"
          alt="Uitdatabank"
          class="udb-logo-mobile"
        />
      </nuxt-link>
      <ul>
        <li>
          <nuxt-link to="/dashboard">
            <fa icon="home" />
            <span>{{ $t('menu.home') }}</span>
          </nuxt-link>
        </li>
        <li>
          <nuxt-link to="/event">
            <fa icon="plus-circle" />
            <span>{{ $t('menu.add') }}</span>
          </nuxt-link>
        </li>
        <li>
          <nuxt-link to="/search">
            <fa icon="search" />
            <span>{{ $t('menu.search') }}</span>
          </nuxt-link>
        </li>
      </ul>
      <div v-if="showExtraMenuItems" class="management-block">
        <p class="management-title">{{ $t('menu.management') }}</p>
        <ul class="admin">
          <li v-if="isValidateVisible">
            <nuxt-link to="/manage/moderation/overview" class="moderation-link">
              <span>
                <fa icon="flag" />
                <span>{{ $t('menu.validate') }}</span>
              </span>
              <span>
                <span v-if="moderationCount > 0" class="badge">{{
                  moderationCount
                }}</span>
              </span>
            </nuxt-link>
          </li>
          <li v-if="isUsersVisible">
            <nuxt-link to="/manage/users/overview">
              <fa icon="user" />
              <span>{{ $t('menu.users') }}</span>
            </nuxt-link>
          </li>
          <li v-if="isRolesVisible">
            <nuxt-link to="/manage/roles/overview">
              <fa icon="users" />
              <span>{{ $t('menu.roles') }}</span>
            </nuxt-link>
          </li>
          <li v-if="isLabelsVisible">
            <nuxt-link to="/manage/labels/overview">
              <fa icon="tag" />
              <span>{{ $t('menu.labels') }}</span>
            </nuxt-link>
          </li>
          <li v-if="isOrganisationsVisible">
            <nuxt-link to="/manage/organizations">
              <fa :icon="['fab', 'slideshare']" />
              <span>{{ $t('menu.organizations') }}</span>
            </nuxt-link>
          </li>
          <li v-if="isProductionsVisible">
            <nuxt-link to="/manage/productions">
              <fa icon="layer-group" />
              <span>{{ $t('menu.productions') }}</span>
            </nuxt-link>
          </li>
        </ul>
      </div>

      <div class="person-data">
        <ul>
          <li>
            <giftbox />
          </li>
          <li class="notifications">
            <a class="notification-container" @click="toggleJobLogger">
              <div>
                <fa icon="bell" />
                <span>{{ $t('menu.notifications') }}</span>
              </div>
              <job-indicator :state="jobLoggerState" />
            </a>
          </li>
          <li class="hidden-xs">
            <div class="media">
              <div class="media-left">
                <!-- TODO: Get the user image -->
                <img
                  class="media-object"
                  width="50"
                  height="50"
                  :src="picture"
                />
              </div>
              <div class="media-body">
                <span class="nick">
                  {{ user.nick ? user.nick : user.username }}
                </span>
                <br />
                <button-logout />
              </div>
            </div>
          </li>
        </ul>

        <!--
        <div class="visible-xs profile-pic dropup">
          <img
            class="img-responsive dropdown-toggle"
            id="logoutMenu"
            data-toggle="dropdown"
            aria-haspopup="true"
            aria-expanded="true"
            width="50"
            height="50"
            src="images/avatar.svg"
          />
          <ul class="dropdown-menu pull-left" aria-labelledby="logoutnMenu">
            <li><a href="#" ng-click="mbc.logout()" translate-once="menu."></a></li>
          </ul>
        </div>
        -->
      </div>
    </div>

    <job-logger
      :is-open="isJobLoggerOpen"
      @close="toggleJobLogger"
      @statechange="handleStateChange"
    />
  </div>
</template>

<script>
  import JobLogger, { JobLoggerStates } from '../components/job/job-logger';
  import ButtonLogout from './button-logout';
  import JobIndicator from './job/job-indicator';
  import Giftbox from './giftbox';

  const Permissions = {
    AANBOD_BEWERKEN: 'AANBOD_BEWERKEN',
    AANBOD_MODEREREN: 'AANBOD_MODEREREN',
    AANBOD_VERWIJDEREN: 'AANBOD_VERWIJDEREN',
    ORGANISATIES_BEWERKEN: 'ORGANISATIES_BEWERKEN',
    ORGANISATIES_BEHEREN: 'ORGANISATIES_BEHEREN',
    GEBRUIKERS_BEHEREN: 'GEBRUIKERS_BEHEREN',
    LABELS_BEHEREN: 'LABELS_BEHEREN',
    VOORZIENINGEN_BEWERKEN: 'VOORZIENINGEN_BEWERKEN',
    PRODUCTIES_AANMAKEN: 'PRODUCTIES_AANMAKEN',
  };

  export default {
    name: 'Sidebar',
    components: {
      ButtonLogout,
      JobIndicator,
      JobLogger,
      Giftbox,
    },
    data() {
      return {
        isJobLoggerOpen: false,
        jobLoggerState: JobLoggerStates.IDLE,
        permissions: [],
        roles: [],
        moderationCount: 0,
      };
    },
    computed: {
      isValidateVisible() {
        return this.roles.some((role) =>
          role.permissions.includes(Permissions.AANBOD_MODEREREN),
        );
      },
      isUsersVisible() {
        return this.permissions.includes(Permissions.GEBRUIKERS_BEHEREN);
      },
      isRolesVisible() {
        return this.permissions.includes(Permissions.GEBRUIKERS_BEHEREN);
      },
      isLabelsVisible() {
        return this.permissions.includes(Permissions.LABELS_BEHEREN);
      },
      isOrganisationsVisible() {
        return this.permissions.includes(Permissions.ORGANISATIES_BEHEREN);
      },
      isProductionsVisible() {
        return this.permissions.includes(Permissions.PRODUCTIES_AANMAKEN);
      },
      showExtraMenuItems() {
        return [
          this.isValidateVisible,
          this.isUsersVisible,
          this.isRolesVisible,
          this.isLabelsVisible,
          this.isOrganisationsVisible,
          this.isProductionsVisible,
        ].includes(true);
      },
      token() {
        return this.$cookies.get('token');
      },
      user() {
        return this.$cookies.get('user');
      },
      picture() {
        return (
          this.$cookies.get('userPicture') || require('../assets/avatar.svg')
        );
      },
    },
    async mounted() {
      const permissions = await this.$api.user.getPermissions();
      const roles = await this.$api.user.getRoles();
      this.permissions = permissions;
      this.roles = roles;

      const validationQuery = this.roles
        .map((role) =>
          role.constraints !== undefined && role.constraints.v3
            ? role.constraints.v3
            : null,
        )
        .filter((constraint) => constraint !== null)
        .join(' OR ');

      const eventsToModerate = await this.$api.events.findEventsToModerate(
        `(${validationQuery})`,
      );

      this.moderationCount = eventsToModerate.totalItems;
    },
    methods: {
      toggleJobLogger() {
        this.isJobLoggerOpen = !this.isJobLoggerOpen;
      },
      handleStateChange(state) {
        this.jobLoggerState = state;
      },
    },
  };
</script>

<style lang="scss">
  $sidebar-width: 230px;
  $sidebar-mobile-width: 65px;
  $padding-normal: 5px;
  $padding-small: 3px;

  .sidebar {
    position: relative;
    width: $sidebar-width;
    padding: $padding-normal;
    background-color: #c0120c;
    height: 100vh;
    color: #fff;
    text-align: left;
    z-index: 2000;
    padding: 5px;

    .udb-logo-link {
      display: block;
    }
    .udb-logo {
      display: block;
      width: 220px;
      height: 40px;
      margin-bottom: 10px;
    }
    .udb-logo-mobile {
      display: none;
    }

    ul {
      list-style: none;
      padding: 0;
      margin: 0;
    }

    a:not(.udb-logo-link) {
      line-height: 1.6rem;
      color: #fff;
      display: inline-block;
      align-items: center;
      text-decoration: none;
      padding: $padding-normal;
      width: 100%;
      font-weight: 600;
    }

    svg:not(:root).svg-inline--fa {
      overflow: visible;
      width: 1rem;
      height: 1rem;
    }

    a .svg-inline--fa {
      margin-right: 6px;
    }

    a:hover:not(.udb-logo-link) {
      background-color: #900d09;
      color: $white;
      text-decoration: none;
      cursor: pointer;
    }

    a.moderation-link {
      display: inline-flex;
      justify-content: space-between;
    }

    .management-block {
      margin-top: 0.8rem;
      border-top: 1px solid #900d09;

      .management-title {
        font-size: small;
        font-weight: normal;
        text-transform: uppercase;
        display: block;
        margin: 5px 0;
        opacity: 0.5;
      }
    }

    a.giftbox-container {
      display: inline-flex;
      justify-content: space-between;
    }

    .notifications {
      border-bottom: 1px solid #900d09;
      margin-bottom: 10px;

      .notification-container {
        display: inline-flex;
        justify-content: space-between;
      }

      .indicator {
        position: absolute;
        right: 0;
        top: 0;
        width: 40px;
      }
    }

    .person-data {
      position: absolute;
      right: 5px;
      bottom: 5px;
      left: 5px;
    }

    .media {
      .media-left {
        padding-right: 10px;
      }
    }
  }

  @media (max-width: 767px) {
    .sidebar {
      width: $sidebar-mobile-width;
      padding: 2px 0;

      a:not(.udb-logo-link) {
        display: flex;
        flex-direction: column;
        justify-content: center;
        font-size: 0.6rem;
        padding: $padding-small;
        width: 100%;
        text-align: center;
        padding-top: $padding-small * 3;
      }

      a div {
        max-width: 100%;
      }

      a span {
        margin-left: 0;
        display: block;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
      }

      .udb-logo-link {
        margin-bottom: 10px;
      }

      .udb-logo {
        display: none;
      }

      .udb-logo-mobile {
        display: block;
        width: 50px;
        height: 50px;
        margin: 0 auto;
      }

      .management-title {
        text-align: center;
      }

      .notifications {
        .notification-container span {
          line-height: 0.8rem;
        }

        #indicator svg {
          margin-top: -50px;
          margin-right: 0;
        }
      }

      svg:not(:root).svg-inline--fa {
        margin: 0 auto;
      }

      .media {
        .media-body {
          display: none;
        }

        .media-left {
          padding-right: 0;
          margin: 0 auto;
        }
      }
    }
  }
</style>
