// src/layouts/joblogger/JobLogger.tsx
import type { Dispatch, SetStateAction } from 'react';
import { useEffect, useMemo, useState } from 'react';
import { useTranslation } from 'react-i18next';

import {
  SocketMessageTypes,
  useHandleSocketMessage,
} from '@/hooks/useHandleSocketMessage';
import {
  useHandleWindowMessage,
  WindowMessageTypes,
} from '@/hooks/useHandleWindowMessage';
import type { Values } from '@/types/Values';
import { Box } from '@/ui/Box';
import { Button, ButtonVariants } from '@/ui/Button';
import { Icon, Icons } from '@/ui/Icon';
import { Inline } from '@/ui/Inline';
import { List } from '@/ui/List';
import { Stack } from '@/ui/Stack';
import { getValueFromTheme } from '@/ui/theme';
import type { TitleProps } from '@/ui/Title';
import { Title } from '@/ui/Title';

import type { JobType } from './Job';
import { Job, JobStates } from './Job';

const getValueForJobLogger = getValueFromTheme('jobLogger');

const JobLoggerStates = {
  IDLE: 'idle',
  WARNING: 'warning',
  BUSY: 'busy',
  COMPLETE: 'complete',
} as const;

const JobTitle = ({ children, className, ...props }: TitleProps) => (
  <Title
    css={`
      width: 100%;
      font-size: 1rem;
      text-transform: uppercase;
      border-bottom: black 1px solid;
    `}
    className={className}
    {...props}
  >
    {children}
  </Title>
);

type JobLoggerProps = {
  visible: boolean;
  onClose: () => void;
  onStatusChange: Dispatch<SetStateAction<Values<typeof JobLoggerStates>>>;
};

const JobLogger = ({ visible, onClose, onStatusChange }: JobLoggerProps) => {
  const { t } = useTranslation();

  const [jobs, setJobs] = useState<JobType[]>([]);
  const [hiddenJobIds, setHiddenJobIds] = useState([]);

  const activeJobs = useMemo(
    () => jobs.filter((job) => !hiddenJobIds.includes(job.id)),
    [jobs, hiddenJobIds],
  );

  const finishedJobs = useMemo(
    () => activeJobs.filter((job) => job.state === JobStates.FINISHED),
    [activeJobs],
  );
  const failedJobs = useMemo(
    () => activeJobs.filter((job) => job.state === JobStates.FAILED),
    [activeJobs],
  );
  const queuedJobs = useMemo(
    () => [
      ...activeJobs.filter((job) => job.state === JobStates.STARTED),
      ...activeJobs.filter((job) => job.state === JobStates.CREATED),
    ],
    [activeJobs],
  );

  const updateJobState =
    (newJobState: Values<typeof JobStates>) =>
    ({
      job_id: jobId,
      location,
    }: {
      // eslint-disable-next-line camelcase
      job_id: string;
      location: string;
    }) =>
      setJobs((previousJobs) =>
        previousJobs.map((job) => {
          const { id, finishedAt, exportUrl, state } = job;
          if (id !== jobId) return job;

          if (state === JobStates.FAILED) {
            // Jobs can't transition from a failed status to another status.
            return job;
          }

          return {
            ...job,
            state: newJobState,
            finishedAt: (
              [JobStates.FINISHED, JobStates.FAILED] as Array<
                Values<typeof JobStates>
              >
            ).includes(newJobState)
              ? new Date()
              : finishedAt,
            exportUrl: location || exportUrl,
          };
        }),
      );

  const addJob = ({ job }: { job: JobType }) =>
    setJobs((previousJobs) => [
      {
        ...job,
        state: JobStates.CREATED,
        exportUrl: '',
        createdAt: new Date(),
      },
      ...previousJobs,
    ]);

  const handleClickHideJob = (id) =>
    setHiddenJobIds((prevHiddenJobIds) => {
      if (prevHiddenJobIds.includes(id)) return prevHiddenJobIds;
      return [...prevHiddenJobIds, id];
    });

  useHandleSocketMessage({
    [SocketMessageTypes.JOB_STARTED]: updateJobState(JobStates.STARTED),
    [SocketMessageTypes.JOB_INFO]: updateJobState(JobStates.STARTED),
    [SocketMessageTypes.JOB_FINISHED]: updateJobState(JobStates.FINISHED),
    [SocketMessageTypes.JOB_FAILED]: updateJobState(JobStates.FAILED),
    [SocketMessageTypes.EVENT_WAS_LABELED]: (...args) => {
      console.log('EVENT_WAS_LABELED', args);
    },
  });

  useHandleWindowMessage({
    [WindowMessageTypes.JOB_ADDED]: addJob,
  });

  useEffect(() => {
    if (failedJobs.length > 0) {
      onStatusChange(JobLoggerStates.WARNING);
      return;
    }
    if (finishedJobs.length > 0) {
      onStatusChange(JobLoggerStates.COMPLETE);
      return;
    }
    if (queuedJobs.length > 0) {
      onStatusChange(JobLoggerStates.BUSY);
      return;
    }
    onStatusChange(JobLoggerStates.IDLE);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [failedJobs, finishedJobs, queuedJobs]);

  const jobLoggerMenus = [
    {
      title: t('jobs.finished'),
      items: finishedJobs,
    },
    {
      title: t('jobs.notifications'),
      items: failedJobs,
    },
    {
      title: t('jobs.in_progress'),
      items: queuedJobs,
    },
  ];

  return (
    <Inline
      css={`
        ${visible && 'display: none;'}
      `}
      position="absolute"
      height="100%"
      width={{ default: 'calc(100% - 230px)', s: 'calc(100% - 65px)' }}
      left={{ default: 230, s: 65 }}
      zIndex={getValueForJobLogger('zIndex')}
    >
      <Stack padding={3} width={320} backgroundColor="white">
        <Inline as="div" justifyContent="flex-end">
          <Button variant={ButtonVariants.UNSTYLED} onClick={onClose}>
            <Icon name={Icons.TIMES} opacity={{ default: 0.5, hover: 1 }} />
          </Button>
        </Inline>
        <Stack spacing={4}>
          {jobLoggerMenus.map((jobLoggerMenu) => (
            <Stack key={jobLoggerMenu.title}>
              <JobTitle>{jobLoggerMenu.title}</JobTitle>
              <List>
                {jobLoggerMenu.items.map((job) => (
                  <Job
                    key={job.id}
                    createdAt={job.createdAt}
                    finishedAt={job.finishedAt}
                    state={job.state}
                    messages={job.messages}
                    exportUrl={job.exportUrl}
                    onClick={() => handleClickHideJob(job.id)}
                  />
                ))}
              </List>
            </Stack>
          ))}
        </Stack>
      </Stack>
      <Box flex={1} opacity={0.5} backgroundColor="black" onClick={onClose} />
    </Inline>
  );
};

export { JobLogger, JobLoggerStates };

// components/job/job-logger.vue
<template>
  <div>
    <div class="udb-job-log" :class="{ open: isOpen }">
      <div class="udb-job-log-header">
        <div class="row">
          <div class="col-sm-12">
            <button type="button" class="close" @click="handleClickClose">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="col-sm-12">
            <div class="udb-job-log-header-message">
              <!-- udb-job-log-header-message -->
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-12">
          <div class="udb-job-block udb-job-block-ready">
            <p class="udb-job-title">{{ $t('jobs.exported_documents') }}</p>
            <ul class="list-unstyled udb-job-messages">
              <job
                v-for="job in finishedExportJobs"
                :id="job.id"
                :key="job.id"
                :created-at="job.createdAt"
                :finished-at="job.finishedAt"
                :state="job.state"
                :messages="job.messages"
                :export-url="job.exportUrl"
                @hide="hideJob"
              />
            </ul>
          </div>

          <div class="udb-job-block udb-job-block-errors">
            <p class="udb-job-title">{{ $t('jobs.notifications') }}</p>
            <ul class="list-unstyled udb-job-messages">
              <job
                v-for="job in failedJobs"
                :id="job.id"
                :key="job.id"
                :created-at="job.createdAt"
                :finished-at="job.finishedAt"
                :state="job.state"
                :messages="job.messages"
                @hide="hideJob"
              />
            </ul>
          </div>

          <div class="udb-job-block udb-job-block-pending">
            <p class="udb-job-title">{{ $t('jobs.in_progress') }}</p>
            <ul class="list-unstyled udb-job-messages">
              <job
                v-for="job in queuedJobs"
                :id="job.id"
                :key="job.id"
                :created-at="job.createdAt"
                :finished-at="job.finishedAt"
                :state="job.state"
                :messages="job.messages"
              />
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div v-show="isOpen" class="udb-job-log-overlay"></div>
  </div>
</template>

<script>
  import { MessageSources, MessageTypes } from '../../services/messages';
  import Job, { JobStates, JobTypes } from './job';

  export const JobLoggerStates = {
    IDLE: 'idle',
    WARNING: 'warning',
    BUSY: 'busy',
    COMPLETE: 'complete',
  };

  export default {
    name: 'JobLogger',
    components: {
      Job,
    },
    props: {
      isOpen: {
        type: Boolean,
        default: false,
      },
    },
    data() {
      return {
        hiddenJobIds: [],
        jobs: [],
      };
    },
    computed: {
      state() {
        if (this.hasFailedJobs) {
          return JobLoggerStates.WARNING;
        }

        if (this.hasCompletedJobs) {
          return JobLoggerStates.COMPLETE;
        }

        if (this.hasActiveJobs) {
          return JobLoggerStates.BUSY;
        }

        return JobLoggerStates.IDLE;
      },
      hasActiveJobs() {
        return this.queuedJobs.length > 0;
      },
      hasCompletedJobs() {
        return this.filterJobsOnState(JobStates.FINISHED).length > 0;
      },
      hasFailedJobs() {
        return this.failedJobs.length > 0;
      },
      newJobs() {
        return this.filterJobsOnState(JobStates.CREATED);
      },
      startedExportJobs() {
        return this.filterJobsOnState(JobStates.STARTED);
      },
      finishedExportJobs() {
        return this.filterJobsOnState(JobStates.FINISHED).filter((job) => {
          return job.type === JobTypes.EXPORT;
        });
      },
      failedJobs() {
        return this.filterJobsOnState(JobStates.FAILED);
      },
      queuedJobs() {
        return this.startedExportJobs.concat(this.newJobs);
      },
    },
    watch: {
      state(state) {
        this.$emit('statechange', state);
      },
    },
    mounted() {
      this.socket = this.$nuxtSocket({});

      this.socket.on('job_started', this.jobStartedHandler);
      this.socket.on('job_info', this.jobInfoHandler);
      this.socket.on('job_finished', this.jobFinishedHandler);
      this.socket.on('job_failed', this.jobFailedHandler);

      window.addEventListener('message', this.handleMessage);
    },
    beforeDestroy() {
      this.socket.close();
      window.removeEventListener('message', this.handleMessage);
    },
    methods: {
      addJob(data) {
        this.jobs.unshift({ state: JobStates.CREATED, exportUrl: '', ...data });
      },
      filterJobsOnState(state) {
        return this.jobs.filter(
          (job) => !this.hiddenJobIds.includes(job.id) && job.state === state,
        );
      },
      findJob(id) {
        return this.jobs.find((job) => job.id === id);
      },
      hideJob(id) {
        if (this.hiddenJobIds.includes(id)) return;
        this.hiddenJobIds.push(id);
      },
      updateJobState(id, state) {
        const job = this.findJob(id);
        if (!job) return;

        if ([JobStates.FAILED, JobStates.FINISHED].includes(job.state)) {
          // Don't update job's that already have a failed or finished state.
          // Due to how socket messages are sent, we might otherwise set a failed state as finished.
          return;
        }

        job.state = state;

        if (
          job.state === JobStates.FINISHED ||
          job.state === JobStates.FAILED
        ) {
          job.finishedAt = new Date();
        }
      },
      handleClickClose() {
        this.$emit('close');
      },
      handleMessage(event) {
        if (event.data.source !== MessageSources.UDB) {
          return;
        }

        if (
          event.data.type === MessageTypes.JOB_ADDED &&
          event.data.job !== undefined
        ) {
          this.addJob(event.data.job);
        }
      },
      /* eslint-disable camelcase */
      jobStartedHandler({ job_id }) {
        this.updateJobState(job_id, JobStates.STARTED);
      },
      jobInfoHandler({ job_id, location }) {
        if (!location) {
          return;
        }

        const job = this.findJob(job_id);
        if (!job) {
          return;
        }

        job.exportUrl = location;
      },
      jobFinishedHandler({ job_id }) {
        this.updateJobState(job_id, JobStates.FINISHED);
      },
      jobFailedHandler({ job_id }) {
        this.updateJobState(job_id, JobStates.FAILED);
      },
      /* eslint-enable camelcase */
    },
  };
</script>

<style lang="scss" scoped>
  .list-unstyled {
    padding-left: 0;
    list-style: none;
  }
  .udb-job-log {
    width: 320px;
    left: -90px;
    right: 0;
    position: fixed;
    top: 0px;
    bottom: 0;
    transition: left 0.3s ease;
    overflow-x: hidden;
    overflow-y: auto;
    background: #ffffff;
    border-right: silver;
    padding: 10px;
    z-index: 1029;
  }

  /*
  .repeat-animation.ng-enter {
    -webkit-transition: all linear 1s;
    -moz-transition: all linear 1s;
    -o-transition: all linear 1s;
    transition: all linear 1s;
  }
  .repeat-animation.ng-enter {
    opacity: 0;
  }
  .repeat-animation.ng-enter.ng-enter-active {
    opacity: 1;
  }
  */

  .udb-job-log.open {
    left: 230px;
  }
  .udb-hide-job-button {
    position: absolute;
    right: 0;
  }
  .udb-hide-job-button:hover {
    cursor: pointer;
  }
  .udb-job-title {
    text-transform: uppercase;
    font-weight: bold;
    border-bottom: 1px solid #000;
  }
  .udb-job-date {
    text-decoration: none;
    color: #777;
    font-size: 0.75em;
    display: block;
  }
  .udb-job-success {
    color: #5cb85c;
  }
  .udb-job-busy {
    color: #5bc0de;
  }

  .udb-job-log-overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background: #000;
    opacity: 0.5;
    z-index: 2;
    display: block;
  }

  @media (max-width: 767px) {
    .udb-job-log {
      width: 275px;
      left: -275px;
    }
    .udb-job-log.open {
      left: 65px;
    }
  }

  .close {
    float: right;
    font-size: 21px;
    font-weight: bold;
    line-height: 1;
    color: #000000;
    text-shadow: 0 1px 0 #ffffff;
    opacity: 0.2;
    filter: alpha(opacity=20);
    padding: 0;
    cursor: pointer;
    background: transparent;
    border: 0;
    -webkit-appearance: none;
  }
  .close:hover,
  .close:focus {
    color: #000000;
    text-decoration: none;
    cursor: pointer;
    opacity: 0.5;
    filter: alpha(opacity=50);
  }
</style>
